package generate

import (
	"bytes"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"

	"cuelang.org/go/cue"
	"cuelang.org/go/encoding/toml"
	"cuelang.org/go/encoding/yaml"
)

// generatedMessage is the format-agnostic header text added to generated files.
const generatedMessage = "Generated by bbcue. DO NOT EDIT."

// commentHeader returns a comment header for the given format, or empty string
// if the format does not support comments.
func commentHeader(format string) string {
	prefix := ""
	switch format {
	case "yaml", "toml":
		prefix = "# "
	default:
		return ""
	}
	return prefix + generatedMessage + "\n\n"
}

// inferFormat returns the format string for a given output filename based on
// its extension. It returns an error if the extension is not recognized.
func inferFormat(filename string) (string, error) {
	ext := strings.ToLower(filepath.Ext(filename))
	switch ext {
	case ".json":
		return "json", nil
	case ".yaml", ".yml":
		return "yaml", nil
	case ".toml":
		return "toml", nil
	case ".txt":
		return "text", nil
	default:
		return "", fmt.Errorf("cannot infer format from filename %q: unrecognized extension %q", filename, ext)
	}
}

// marshalContent encodes a CUE value into bytes using the specified format.
func marshalContent(val cue.Value, format string) ([]byte, error) {
	switch format {
	case "json":
		b, err := val.MarshalJSON()
		if err != nil {
			return nil, fmt.Errorf("json marshal: %w", err)
		}
		// Pretty-print with indentation.
		var buf bytes.Buffer
		if err := json.Indent(&buf, b, "", "  "); err != nil {
			return nil, fmt.Errorf("json indent: %w", err)
		}
		buf.WriteByte('\n')
		return buf.Bytes(), nil

	case "yaml":
		b, err := yaml.Encode(val)
		if err != nil {
			return nil, fmt.Errorf("yaml marshal: %w", err)
		}
		return append([]byte(commentHeader(format)), b...), nil

	case "toml":
		var buf bytes.Buffer
		buf.WriteString(commentHeader(format))
		enc := toml.NewEncoder(&buf)
		if err := enc.Encode(val); err != nil {
			return nil, fmt.Errorf("toml marshal: %w", err)
		}
		return buf.Bytes(), nil

	case "text":
		s, err := val.String()
		if err != nil {
			return nil, fmt.Errorf("text marshal: %w", err)
		}
		if !strings.HasSuffix(s, "\n") {
			s += "\n"
		}
		return []byte(s), nil

	default:
		return nil, fmt.Errorf("unsupported format: %q", format)
	}
}
